replicaCount: 2

image:
  repository: europe-west1-docker.pkg.dev/vdxl-mgmt-01/vdxl-mgmt-01-product-content/hub-api-service
  tag: ""

container:
  name: hub-api-service
  port: 7080

service:
  port: 80

serviceAccount:
  name: ai-hub

resources:
  requests:
    cpu: 150m
    memory: 256Mi

env:
  - name: TZ
    value: "Europe/Amsterdam"

podLabels:
  admission.datadoghq.com/enabled: "true"

podAnnotations:
  admission.datadoghq.com/java-lib.version: "v1"
  admission.datadoghq.com/java-lib.enabled: "true"

probes:
  readiness:
    enabled: true
    httpGet:
      path: /actuator/health
      port: 7080
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

  liveness:
    enabled: true
    httpGet:
      path: /actuator/health
      port: 7080
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75

gateway:
  enabled: true
  routes:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: hub-api-service
          port: 80
