replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
  
service:
  port: 80
  targetPort: 80

ports: []
env: []
resources: {}

readinessProbe: {}
livenessProbe: {}

route:
  enabled: false

autoscaling:
  enabled: false
